sudo: required
language: node_js
node_js:
  - "10"
cache:
  bundler: false
  yarn: true
  directories:
  - .build-cache
git:
  submodules: false
install: true

jobs:
  include:
    - stage: test
      name: "Unit tests and code checks"
      install: yarn install --frozen-lockfile --non-interactive --audit --silent
      script:
        - yarn format:check
        - yarn lint
        - yarn test
    - stage: build
      language: bash
      name: "Build the docker image"
      node_js:
      services:
        - docker
#      before_install:
#        - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
#        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ;
      install: skip
      script: docker build -f tools/docker/dev.Dockerfile -t flogo/flogo-web:master  .
      after_script:
        - "[ -f \"${HOME}/.netrc\" ] && rm -f ${HOME}/.netrc"
#      after_success:
#        - "if [ \"${TRAVIS_BRANCH}\" == \"master\" ]; then
#          docker push flogo/flogo-web:master ;
#          fi"
