version: '2'
services:
  flogo-web:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "3010:3010"
      - "5984:5984"
      - "8080:8080"
    environment:
      FLOGO_FLOW_SERVICE_HOST: flow-service
      FLOGO_FLOW_STATE_SERVICE_HOST: flow-state-service
    depends_on:
     - flow-service
     - flow-state-service
  flow-service:
    image: flogo/flow-service
    ports:
      - "9090:9090"
  flow-state-service:
    image: flogo/flow-state-service
    ports:
      - "9190:9190"
