version: '2'
services:
  flogo-web:
      image: ${DOCKER_REGISTRY}flogo/flow-web:${BUILD_RELEASE_TAG}
#      build:
#        context: .
#        dockerfile: Dockerfile
      ports:
        - "3010:3010"
        - "5984:5984"
        - "8080:8080"
      environment:
        FLOGO_FLOW_SERVICE_HOST: flogo-flow-service
        FLOGO_FLOW_STATE_SERVICE_HOST: flogo-state-service
        FLOGO_FLOW_WEB_HOST: ${DOCKER_HOST}
        FLOGO_NO_ENGINE_RECREATION: "true"
      depends_on:
        - flogo-flow-service
        - flogo-state-service
  flogo-redis:
        image: redis
  flogo-flow-service:
        image: ${DOCKER_REGISTRY}flogo/flow-service:${BUILD_RELEASE_TAG}
        depends_on:
        - flogo-redis
        ports:
        - "9090:9090"
        - "9091:9091"
        links:
        - flogo-redis
        entrypoint:
        - /tmp/flow-service/docker-start.sh
        environment:
        - FLOGO_REDIS_HOST=flogo-redis
  flogo-state-service:
        image: ${DOCKER_REGISTRY}flogo/state-service:${BUILD_RELEASE_TAG}
        depends_on:
        - flogo-redis
        ports:
        - "9190:9190"
        - "9191:9191"
        links:
        - flogo-redis
        entrypoint:
        - /tmp/flow-state-service/docker-start.sh
        environment:
        - FLOGO_REDIS_HOST=flogo-redis
