version: '2'
services:
  flogo-web:
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "3010:3010"
      - "5984:5984"
      - "8080:8080"
    environment:
      FLOGO_FLOW_SERVICES: "flogo-flow-services"
    depends_on:
     - flogo-flow-services
  flogo-flow-services:
    build:
      context: .
      dockerfile: docker/flow-services/Dockerfile
    ports:
     - "9190:9190"
     - "9090:9090"
    depends_on:
     - flogo-redis
  flogo-redis:
    image: redis
  flogo-toke-mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
